/**
 * 오픈소스 라이브러리 목록 — scripts/gen-opensource.mjs 로 자동 생성됩니다.
 * 직접 수정하지 말고 `yarn oss` 를 실행하세요.
 */
export interface OpenSourceLib {
	name: string;
	version: string;
	license: string;
	url: string;
}

export const OPEN_SOURCE_LIBS: OpenSourceLib[] = [
	{ name: '@expo/vector-icons', version: '15.1.1', license: 'MIT', url: 'https://github.com/expo/vector-icons' },
	{ name: '@notifee/react-native', version: '9.1.8', license: 'Apache-2.0', url: 'https://github.com/invertase/notifee' },
	{ name: '@react-native-async-storage/async-storage', version: '2.2.0', license: 'MIT', url: 'https://github.com/react-native-async-storage/async-storage' },
	{ name: '@react-native-community/datetimepicker', version: '8.6.0', license: 'MIT', url: 'https://github.com/react-native-datetimepicker/datetimepicker' },
	{ name: '@react-native-community/netinfo', version: '11.5.2', license: 'MIT', url: 'https://github.com/react-native-netinfo/react-native-netinfo' },
	{ name: '@react-native-firebase/analytics', version: '24.1.1', license: 'Apache-2.0', url: 'https://github.com/invertase/react-native-firebase/tree/main/packages/analytics' },
	{ name: '@react-native-firebase/app', version: '24.1.1', license: 'Apache-2.0', url: 'https://github.com/invertase/react-native-firebase/tree/main/packages/app' },
	{ name: '@react-native-firebase/crashlytics', version: '24.1.1', license: 'Apache-2.0', url: 'https://github.com/invertase/react-native-firebase/tree/main/packages/crashlytics' },
	{ name: '@react-native-picker/picker', version: '2.11.4', license: 'MIT', url: 'https://github.com/react-native-picker/picker' },
	{ name: '@react-navigation/bottom-tabs', version: '7.18.14', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@react-navigation/drawer', version: '7.13.5', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@react-navigation/elements', version: '2.9.36', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@react-navigation/material-top-tabs', version: '7.6.13', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@react-navigation/native', version: '7.3.4', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@react-navigation/stack', version: '7.10.17', license: 'MIT', url: 'https://github.com/react-navigation/react-navigation' },
	{ name: '@reduxjs/toolkit', version: '2.12.0', license: 'MIT', url: 'https://github.com/reduxjs/redux-toolkit' },
	{ name: '@supabase/supabase-js', version: '2.111.0', license: 'MIT', url: 'https://github.com/supabase/supabase-js' },
	{ name: 'axios', version: '1.18.0', license: 'MIT', url: 'https://github.com/axios/axios' },
	{ name: 'expo', version: '55.0.28', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-asset', version: '55.0.18', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-audio', version: '55.0.16', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-build-properties', version: '55.0.16', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-constants', version: '55.0.17', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-font', version: '55.0.8', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-haptics', version: '55.0.16', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-image', version: '55.0.11', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-linear-gradient', version: '55.0.16', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-linking', version: '55.0.16', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-localization', version: '55.0.17', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-router', version: '55.0.17', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-sharing', version: '55.0.22', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-splash-screen', version: '55.0.23', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-status-bar', version: '55.0.6', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'expo-updates', version: '55.0.26', license: 'MIT', url: 'https://github.com/expo/expo' },
	{ name: 'i18next', version: '24.2.3', license: 'MIT', url: 'https://github.com/i18next/i18next' },
	{ name: 'intl-pluralrules', version: '2.0.1', license: 'ISC', url: 'eemeli/intl-pluralrules' },
	{ name: 'lottie-react-native', version: '7.3.8', license: 'Apache-2.0', url: 'https://github.com/lottie-react-native/lottie-react-native' },
	{ name: 'moment', version: '2.30.1', license: 'MIT', url: 'https://github.com/moment/moment' },
	{ name: 'punycode', version: '2.3.1', license: 'MIT', url: 'https://github.com/mathiasbynens/punycode.js' },
	{ name: 'react', version: '19.2.0', license: 'MIT', url: 'https://github.com/facebook/react' },
	{ name: 'react-i18next', version: '15.7.4', license: 'MIT', url: 'https://github.com/i18next/react-i18next' },
	{ name: 'react-native', version: '0.83.6', license: 'MIT', url: 'https://github.com/facebook/react-native' },
	{ name: 'react-native-animated-numbers', version: '0.6.3', license: 'MIT', url: 'https://github.com/heyman333/react-native-animated-numbers' },
	{ name: 'react-native-base64', version: '0.2.2', license: 'MIT', url: 'https://github.com/eranbo/react-native-base64' },
	{ name: 'react-native-bootsplash', version: '7.3.2', license: 'MIT', url: 'https://github.com/zoontek/react-native-bootsplash' },
	{ name: 'react-native-bouncy-checkbox', version: '4.1.4', license: 'MIT', url: 'git@github.com:WrathChaos/react-native-bouncy-checkbox' },
	{ name: 'react-native-calendars', version: '1.1314.0', license: 'MIT', url: 'https://github.com/wix/react-native-calendars' },
	{ name: 'react-native-circular-progress', version: '1.4.1', license: 'MIT', url: 'https://github.com/bgryszko/react-native-circular-progress' },
	{ name: 'react-native-confetti-cannon', version: '1.5.2', license: 'MIT', url: 'https://github.com/vincentcatillon/react-native-confetti-cannon' },
	{ name: 'react-native-device-info', version: '14.1.1', license: 'MIT', url: 'https://github.com/react-native-device-info/react-native-device-info' },
	{ name: 'react-native-dropdown-picker', version: '5.4.6', license: 'MIT', url: 'https://github.com/hossein-zare/react-native-dropdown-picker' },
	{ name: 'react-native-flip-card', version: '3.5.7', license: 'MIT', url: 'https://github.com/moschan/react-native-flip-card' },
	{ name: 'react-native-gesture-handler', version: '2.30.1', license: 'MIT', url: 'https://github.com/software-mansion/react-native-gesture-handler' },
	{ name: 'react-native-google-mobile-ads', version: '14.11.0', license: 'Apache-2.0', url: 'https://github.com/invertase/react-native-google-mobile-ads' },
	{ name: 'react-native-iap', version: '16.0.1', license: 'MIT', url: 'https://github.com/hyodotdev/openiap' },
	{ name: 'react-native-in-app-review', version: '4.4.2', license: 'MIT', url: 'https://github.com/MinaSamir11/react-native-in-app-review' },
	{ name: 'react-native-linear-gradient', version: '2.8.3', license: 'MIT', url: 'https://github.com/react-native-linear-gradient/react-native-linear-gradient' },
	{ name: 'react-native-markdown-display', version: '7.0.2', license: 'MIT', url: 'https://github.com/iamacup/react-native-markdown-display' },
	{ name: 'react-native-nitro-modules', version: '0.36.5', license: 'MIT', url: 'https://github.com/mrousavy/nitro' },
	{ name: 'react-native-pager-view', version: '8.0.0', license: 'MIT', url: 'https://github.com/callstack/react-native-pager-view' },
	{ name: 'react-native-permissions', version: '5.6.1', license: 'MIT', url: 'https://github.com/zoontek/react-native-permissions' },
	{ name: 'react-native-reanimated', version: '4.2.3', license: 'MIT', url: 'https://github.com/software-mansion/react-native-reanimated' },
	{ name: 'react-native-safe-area-context', version: '5.6.2', license: 'MIT', url: 'https://github.com/AppAndFlow/react-native-safe-area-context' },
	{ name: 'react-native-screens', version: '4.23.0', license: 'MIT', url: 'https://github.com/software-mansion/react-native-screens' },
	{ name: 'react-native-svg', version: '15.15.3', license: 'MIT', url: 'https://github.com/react-native-community/react-native-svg' },
	{ name: 'react-native-swipe-list-view', version: '3.2.9', license: 'MIT', url: 'https://github.com/jemise111/react-native-swipe-list-view' },
	{ name: 'react-native-url-polyfill', version: '4.0.0', license: 'MIT', url: 'https://github.com/charpeni/react-native-url-polyfill' },
	{ name: 'react-native-vector-icons', version: '10.3.0', license: 'MIT', url: 'https://github.com/oblador/react-native-vector-icons' },
	{ name: 'react-native-version-check', version: '3.5.0', license: 'MIT', url: 'https://github.com/kimxogus/react-native-version-check' },
	{ name: 'react-native-view-shot', version: '4.0.3', license: 'MIT', url: 'https://github.com/gre/react-native-view-shot' },
	{ name: 'react-native-worklets', version: '0.7.4', license: 'MIT', url: 'https://github.com/software-mansion/react-native-reanimated' },
	{ name: 'react-redux', version: '9.3.0', license: 'MIT', url: 'https://github.com/reduxjs/react-redux' },
	{ name: 'redux-logger', version: '3.0.6', license: 'MIT', url: 'https://github.com/theaqua/redux-logger' },
	{ name: 'redux-persist', version: '6.0.0', license: 'MIT', url: 'rt2zz/redux-persist' },
	{ name: 'zod', version: '3.25.76', license: 'MIT', url: 'https://github.com/colinhacks/zod' },
];

export default OPEN_SOURCE_LIBS;
