export enum MainStorageKeyType {
	TODAY_QUIZ_LIST = 'TodayQuizList',
	USER_STUDY_HISTORY = 'UserStudyHistory', // 학습
	TIME_CHALLENGE_HISTORY = 'TimeChallengeHistory', // 챌린지
	USER_QUIZ_HISTORY = 'UserQuizHistory', // 퀴즈
	SETTING_INFO = 'SettingInfo',
	AD_REMOVED = 'AD_REMOVED',
	USER_PROVERB_BOOKS = 'USER_PROVERB_BOOKS',
	TOWER_CHALLENGE_PROGRESS = 'TOWER_CHALLENGE_PROGRESS',
	USER_PROVERB_PRACTICE_RECORDS = 'USER_PROVERB_PRACTICE_RECORDS',
	FAVORITES_STORAGE_KEY = 'FAVORITES_STORAGE_KEY',
	DAILY_MISSION_CLAIMED = 'DAILY_MISSION_CLAIMED', // 일일 미션 보상 수령 날짜 목록
	LAST_SEEN_GRADE = 'LAST_SEEN_GRADE', // 마지막으로 확인한 점수 등급 인덱스(레벨업 감지용)
	STREAK_REWARD_CLAIMED = 'STREAK_REWARD_CLAIMED', // 지급 완료된 연속 출석 마일스톤 목록
}
